<?php
$nomes_estilizados_de_todos_os_monstros = [
  ["id" => 1001, "nome" => "Escorpião"],
  ["id" => 1002, "nome" => "Poring"],
  ["id" => 1004, "nome" => "Zangão"],
  ["id" => 1005, "nome" => "Familiar"],
  ["id" => 1007, "nome" => "Fabre"],
  ["id" => 1008, "nome" => "Pupa"],
  ["id" => 1009, "nome" => "Condor"],
  ["id" => 1010, "nome" => "Salgueiro"],
  ["id" => 1011, "nome" => "ChonChon"],
  ["id" => 1012, "nome" => "Sapo de Rodda"],
  ["id" => 1013, "nome" => "Lobo"],
  ["id" => 1014, "nome" => "Esporo"],
  ["id" => 1015, "nome" => "Zumbi"],
  ["id" => 1016, "nome" => "Esqueleto Arqueiro"],
  ["id" => 1018, "nome" => "Creamy"],
  ["id" => 1019, "nome" => "PecoPeco"],
  ["id" => 1020, "nome" => "Mandrágora"],
  ["id" => 1023, "nome" => "Guerreiro Orc"],
  ["id" => 1024, "nome" => "Rabo de Verme"],
  ["id" => 1025, "nome" => "Jibóia"],
  ["id" => 1026, "nome" => "Munak"],
  ["id" => 1028, "nome" => "Esqueleto Soldado"],
  ["id" => 1029, "nome" => "Isis"],
  ["id" => 1030, "nome" => "Anaconda"],
  ["id" => 1031, "nome" => "Poporing"],
  ["id" => 1032, "nome" => "Verit"],
  ["id" => 1033, "nome" => "Salgueiro Ancião"],
  ["id" => 1034, "nome" => "Sapo de Thara"],
  ["id" => 1035, "nome" => "Mosca Caçadora"],
  ["id" => 1036, "nome" => "Carniçal"],
  ["id" => 1037, "nome" => "Sorrateiro"],
  ["id" => 1038, "nome" => "Osíris"],
  ["id" => 1039, "nome" => "Bafomé"],
  ["id" => 1040, "nome" => "Golem"],
  ["id" => 1041, "nome" => "Múmia"],
  ["id" => 1042, "nome" => "ChonChon de Aço"],
  ["id" => 1044, "nome" => "Obeaune"],
  ["id" => 1045, "nome" => "Cavalo-Marinho"],
  ["id" => 1046, "nome" => "Doppelganger"],
  ["id" => 1047, "nome" => "Ovo de PecoPeco"],
  ["id" => 1048, "nome" => "Ovo de Besouro-Ladrão"],
  ["id" => 1049, "nome" => "Picky"],
  ["id" => 1050, "nome" => "Picky com casca"],
  ["id" => 1051, "nome" => "Besouro-Ladrão"],
  ["id" => 1052, "nome" => "Rocker"],
  ["id" => 1053, "nome" => "Besouro-Ladrão Fêmea"],
  ["id" => 1054, "nome" => "Besouro-Ladrão Macho"],
  ["id" => 1055, "nome" => "Muka"],
  ["id" => 1056, "nome" => "Fumacento"],
  ["id" => 1057, "nome" => "Yoyo"],
  ["id" => 1058, "nome" => "Metaller"],
  ["id" => 1059, "nome" => "Abelha-Rainha"],
  ["id" => 1060, "nome" => "Pé-Grande"],
  ["id" => 1061, "nome" => "Pesadelo"],
  ["id" => 1062, "nome" => "Poring Noel"],
  ["id" => 1063, "nome" => "Lunático"],
  ["id" => 1064, "nome" => "Megalodon"],
  ["id" => 1065, "nome" => "Strouf"],
  ["id" => 1066, "nome" => "Vadon"],
  ["id" => 1067, "nome" => "Cornutus"],
  ["id" => 1068, "nome" => "Hidra"],
  ["id" => 1069, "nome" => "Peixe-Espada"],
  ["id" => 1070, "nome" => "Kukre"],
  ["id" => 1071, "nome" => "Esqueleto Pirata"],
  ["id" => 1072, "nome" => "Kaho"],
  ["id" => 1073, "nome" => "Caranguejo"],
  ["id" => 1074, "nome" => "Molusco"],
  ["id" => 1076, "nome" => "Esqueleto"],
  ["id" => 1077, "nome" => "Esporo Venenoso"],
  ["id" => 1078, "nome" => "Planta Vermelha"],
  ["id" => 1079, "nome" => "Planta Azul"],
  ["id" => 1080, "nome" => "Planta Verde"],
  ["id" => 1081, "nome" => "Planta Amarela"],
  ["id" => 1082, "nome" => "Planta Branca"],
  ["id" => 1083, "nome" => "Planta Brilhante"],
  ["id" => 1084, "nome" => "Cogumelo Negro"],
  ["id" => 1085, "nome" => "Cogumelo Vermelho"],
  ["id" => 1086, "nome" => "Besouro-Ladrão Dourado"],
  ["id" => 1087, "nome" => "Orc Herói"],
  ["id" => 1088, "nome" => "Vocal"],
  ["id" => 1089, "nome" => "Sapo-Cururu"],
  ["id" => 1090, "nome" => "Mastering"],
  ["id" => 1091, "nome" => "Libélula"],
  ["id" => 1092, "nome" => "Lobo Errante"],
  ["id" => 1093, "nome" => "Eclipse"],
  ["id" => 1094, "nome" => "Ambernite"],
  ["id" => 1095, "nome" => "Andre"],
  ["id" => 1096, "nome" => "Angeling"],
  ["id" => 1097, "nome" => "Ovo de Andre"],
  ["id" => 1098, "nome" => "Anubis"],
  ["id" => 1099, "nome" => "Argiope"],
  ["id" => 1100, "nome" => "Argos"],
  ["id" => 1101, "nome" => "Bafomé Jr"],
  ["id" => 1102, "nome" => "Bathory"],
  ["id" => 1103, "nome" => "Caramelo"],
  ["id" => 1104, "nome" => "Koko"],
  ["id" => 1105, "nome" => "Deniro"],
  ["id" => 1106, "nome" => "Lobo do Deserto"],
  ["id" => 1107, "nome" => "Filhote de Lobo do Deserto"],
  ["id" => 1108, "nome" => "Deviace"],
  ["id" => 1109, "nome" => "Deviruchi"],
  ["id" => 1110, "nome" => "Dokebi"],
  ["id" => 1111, "nome" => "Drainliar"],
  ["id" => 1112, "nome" => "Drake"],
  ["id" => 1113, "nome" => "Drops"],
  ["id" => 1114, "nome" => "Poeira"],
  ["id" => 1115, "nome" => "Eddga"],
  ["id" => 1116, "nome" => "Eggyra"],
  ["id" => 1117, "nome" => "Druida Maligno"],
  ["id" => 1118, "nome" => "Flora"],
  ["id" => 1119, "nome" => "Frilldora"],
  ["id" => 1120, "nome" => "Ghostring"],
  ["id" => 1121, "nome" => "Giearth"],
  ["id" => 1122, "nome" => "Goblin (adaga)"],
  ["id" => 1123, "nome" => "Goblin (mangual)"],
  ["id" => 1124, "nome" => "Goblin (machado)"],
  ["id" => 1125, "nome" => "Goblin (martelo)"],
  ["id" => 1126, "nome" => "Goblin (maça)"],
  ["id" => 1127, "nome" => "Hode"],
  ["id" => 1128, "nome" => "Besouro-Chifre"],
  ["id" => 1129, "nome" => "Horong"],
  ["id" => 1130, "nome" => "Jakk"],
  ["id" => 1131, "nome" => "Coringa"],
  ["id" => 1132, "nome" => "Khalitzburg"],
  ["id" => 1133, "nome" => "Cobold (machado)"],
  ["id" => 1134, "nome" => "Cobold (martelo)"],
  ["id" => 1135, "nome" => "Cobold (maça)"],
  ["id" => 1138, "nome" => "Magnólia"],
  ["id" => 1139, "nome" => "Louva-a-Deus"],
  ["id" => 1140, "nome" => "Marduk"],
  ["id" => 1141, "nome" => "Marina"],
  ["id" => 1142, "nome" => "Esfera Marinha"],
  ["id" => 1143, "nome" => "Marionete"],
  ["id" => 1144, "nome" => "Marte"],
  ["id" => 1145, "nome" => "Martin"],
  ["id" => 1146, "nome" => "Matyr"],
  ["id" => 1147, "nome" => "Maya"],
  ["id" => 1148, "nome" => "Medusa"],
  ["id" => 1149, "nome" => "Minorous"],
  ["id" => 1150, "nome" => "Flor do Luar"],
  ["id" => 1151, "nome" => "Névoa"],
  ["id" => 1152, "nome" => "Orc Esqueleto"],
  ["id" => 1153, "nome" => "Orc Zumbi"],
  ["id" => 1154, "nome" => "Pasana"],
  ["id" => 1155, "nome" => "Petite Terrestre"],
  ["id" => 1156, "nome" => "Petite Voador"],
  ["id" => 1157, "nome" => "Faraó"],
  ["id" => 1158, "nome" => "Fen"],
  ["id" => 1159, "nome" => "Freeoni"],
  ["id" => 1160, "nome" => "Piere"],
  ["id" => 1161, "nome" => "Plankton"],
  ["id" => 1162, "nome" => "Rafflesia"],
  ["id" => 1163, "nome" => "Raydric"],
  ["id" => 1164, "nome" => "Réquiem"],
  ["id" => 1165, "nome" => "Arenoso"],
  ["id" => 1166, "nome" => "Selvagem"],
  ["id" => 1167, "nome" => "Bebê Selvagem"],
  ["id" => 1169, "nome" => "Esqueleto Operário"],
  ["id" => 1170, "nome" => "Sohee"],
  ["id" => 1174, "nome" => "Percevejo"],
  ["id" => 1175, "nome" => "Tarou"],
  ["id" => 1176, "nome" => "Vitata"],
  ["id" => 1177, "nome" => "Zenorc"],
  ["id" => 1178, "nome" => "Zerom"],
  ["id" => 1179, "nome" => "Sussurro"],
  ["id" => 1180, "nome" => "Nove Caudas"],
  ["id" => 1185, "nome" => "Sussurro"],
  ["id" => 1186, "nome" => "Cochicho"],
  ["id" => 1188, "nome" => "Bongun"],
  ["id" => 1189, "nome" => "Orc Arqueiro"],
  ["id" => 1190, "nome" => "Senhor dos Orcs"],
  ["id" => 1191, "nome" => "Mímico"],
  ["id" => 1192, "nome" => "Alma Penada"],
  ["id" => 1193, "nome" => "Alarme"],
  ["id" => 1194, "nome" => "Arclouse"],
  ["id" => 1195, "nome" => "Rideword"],
  ["id" => 1196, "nome" => "Esqueleto Prisioneiro"],
  ["id" => 1197, "nome" => "Zumbi Prisioneiro"],
  ["id" => 1198, "nome" => "Sacerdote Maldito"],
  ["id" => 1199, "nome" => "Punk"],
  ["id" => 1200, "nome" => "Jirtas"],
  ["id" => 1201, "nome" => "Rybio"],
  ["id" => 1202, "nome" => "Fendark"],
  ["id" => 1203, "nome" => "Mysteltainn"],
  ["id" => 1204, "nome" => "Tyrfing"],
  ["id" => 1205, "nome" => "Executor"],
  ["id" => 1206, "nome" => "Anolian"],
  ["id" => 1207, "nome" => "Sting"],
  ["id" => 1208, "nome" => "Andarilho"],
  ["id" => 1209, "nome" => "Cãibra"],
  ["id" => 1211, "nome" => "Escaravelho"],
  ["id" => 1212, "nome" => "Mão de Ferro"],
  ["id" => 1213, "nome" => "Grand Orc"],
  ["id" => 1214, "nome" => "Choco"],
  ["id" => 1215, "nome" => "Talo de Verme"],
  ["id" => 1216, "nome" => "Penomena"],
  ["id" => 1219, "nome" => "Cavaleiro do Abismo"],
  ["id" => 1242, "nome" => "Marin"],
  ["id" => 1243, "nome" => "Sasquatch"],
  ["id" => 1244, "nome" => "Jakk Natalino"],
  ["id" => 1245, "nome" => "Goblin Natalino"],
  ["id" => 1246, "nome" => "Cookie Natalino"],
  ["id" => 1247, "nome" => "Antonio"],
  ["id" => 1248, "nome" => "Soldadinho de Chumbo"],
  ["id" => 1249, "nome" => "Presente"],
  ["id" => 1250, "nome" => "Chepet"],
  ["id" => 1251, "nome" => "Cavaleiro da Tempestade"],
  ["id" => 1252, "nome" => "Hatii"],
  ["id" => 1253, "nome" => "Gárgula"],
  ["id" => 1254, "nome" => "Raggler"],
  ["id" => 1255, "nome" => "Nereida"],
  ["id" => 1256, "nome" => "Peste"],
  ["id" => 1257, "nome" => "Injustiçado"],
  ["id" => 1258, "nome" => "Goblin Arqueiro"],
  ["id" => 1259, "nome" => "Grifo"],
  ["id" => 1260, "nome" => "Moldura Maldita"],
  ["id" => 1261, "nome" => "Rosa Selvagem"],
  ["id" => 1262, "nome" => "Dragão Mutante"],
  ["id" => 1263, "nome" => "Xamã do Vento"],
  ["id" => 1264, "nome" => "Tritão"],
  ["id" => 1265, "nome" => "Cookie"],
  ["id" => 1266, "nome" => "Estrela-do-Mar"],
  ["id" => 1267, "nome" => "Carat"],
  ["id" => 1268, "nome" => "Cavaleiro Sanguinário"],
  ["id" => 1269, "nome" => "Relógio"],
  ["id" => 1270, "nome" => "Gerente"],
  ["id" => 1271, "nome" => "Crocodilo"],
  ["id" => 1272, "nome" => "Senhor das Trevas"],
  ["id" => 1273, "nome" => "Senhora Orc"],
  ["id" => 1274, "nome" => "Megalith"],
  ["id" => 1275, "nome" => "Alice"],
  ["id" => 1276, "nome" => "Raydric Arqueiro"],
  ["id" => 1277, "nome" => "Guardião da Floresta"],
  ["id" => 1278, "nome" => "Golem Estalactítico"],
  ["id" => 1279, "nome" => "Trilobita"],
  ["id" => 1280, "nome" => "Goblin a Vapor"],
  ["id" => 1281, "nome" => "Verme Sábio"],
  ["id" => 1282, "nome" => "Cobold Arqueiro"],
  ["id" => 1283, "nome" => "Quimera"],
  ["id" => 1288, "nome" => "Emperium"],
  ["id" => 1289, "nome" => "Maya Macho"],
  ["id" => 1290, "nome" => "Esqueleto General"],
  ["id" => 1291, "nome" => "Aparição"],
  ["id" => 1292, "nome" => "Diabinho"],
  ["id" => 1293, "nome" => "Creamy Ameaçador"],
  ["id" => 1294, "nome" => "Mantis Assassino"],
  ["id" => 1295, "nome" => "Barão Coruja"],
  ["id" => 1296, "nome" => "Líder Cobold"],
  ["id" => 1297, "nome" => "Múmia Anciã"],
  ["id" => 1298, "nome" => "Zumbi Mestre"],
  ["id" => 1299, "nome" => "Líder Goblin"],
  ["id" => 1300, "nome" => "Lagarta"],
  ["id" => 1301, "nome" => "Am Mut"],
  ["id" => 1302, "nome" => "Ilusão das Trevas"],
  ["id" => 1303, "nome" => "Zangão Gigante"],
  ["id" => 1304, "nome" => "Aranha Gigante"],
  ["id" => 1305, "nome" => "Verme Ancião"],
  ["id" => 1306, "nome" => "Leib Olmai"],
  ["id" => 1307, "nome" => "Gato de Nove Caudas"],
  ["id" => 1308, "nome" => "Panzer Goblin"],
  ["id" => 1309, "nome" => "Gajomart"],
  ["id" => 1310, "nome" => "Majoruros"],
  ["id" => 1311, "nome" => "Gullinbursti"],
  ["id" => 1312, "nome" => "General Tartaruga"],
  ["id" => 1313, "nome" => "Yakuza"],
  ["id" => 1314, "nome" => "Batedor"],
  ["id" => 1315, "nome" => "Agressor"],
  ["id" => 1316, "nome" => "Soldado"],
  ["id" => 1317, "nome" => "Foca"],
  ["id" => 1318, "nome" => "Aquecedor"],
  ["id" => 1319, "nome" => "Congelador"],
  ["id" => 1320, "nome" => "Duque Coruja"],
  ["id" => 1321, "nome" => "Lavadeira"],
  ["id" => 1322, "nome" => "Coelho"],
  ["id" => 1323, "nome" => "Lontra"],
  ["id" => 1365, "nome" => "Apocalipse"],
  ["id" => 1366, "nome" => "Golem de Lava"],
  ["id" => 1367, "nome" => "Labareda"],
  ["id" => 1368, "nome" => "Planta Carnívora"],
  ["id" => 1369, "nome" => "Grand Peco"],
  ["id" => 1370, "nome" => "Succubus"],
  ["id" => 1371, "nome" => "Anjo Fajuto"],
  ["id" => 1372, "nome" => "Bode"],
  ["id" => 1373, "nome" => "Senhor dos Mortos"],
  ["id" => 1374, "nome" => "Incubus"],
  ["id" => 1375, "nome" => "Papel"],
  ["id" => 1376, "nome" => "Harpia"],
  ["id" => 1377, "nome" => "Ancião"],
  ["id" => 1378, "nome" => "Pungus"],
  ["id" => 1379, "nome" => "Pesadelo Sombrio"],
  ["id" => 1380, "nome" => "Furador"],
  ["id" => 1381, "nome" => "Grizzly"],
  ["id" => 1382, "nome" => "Diabolik"],
  ["id" => 1383, "nome" => "Estrondo"],
  ["id" => 1384, "nome" => "Exterminador"],
  ["id" => 1385, "nome" => "Deletério"],
  ["id" => 1386, "nome" => "Rochoso"],
  ["id" => 1387, "nome" => "Ferrão"],
  ["id" => 1388, "nome" => "ArchAngeling"],
  ["id" => 1389, "nome" => "Drácula"],
  ["id" => 1390, "nome" => "Violi"],
  ["id" => 1391, "nome" => "Galápago"],
  ["id" => 1392, "nome" => "Giro-Goblin"],
  ["id" => 1400, "nome" => "Karakasa"],
  ["id" => 1401, "nome" => "Shinobi"],
  ["id" => 1402, "nome" => "Sapo Venenoso"],
  ["id" => 1403, "nome" => "Soldado Atirador"],
  ["id" => 1404, "nome" => "Boneco de Miyabi"],
  ["id" => 1405, "nome" => "Tengu"],
  ["id" => 1406, "nome" => "Kapha"],
  ["id" => 1408, "nome" => "Borboleta Sanguinária"],
  ["id" => 1409, "nome" => "Pirralho"],
  ["id" => 1410, "nome" => "Pessegueira Encantada"],
  ["id" => 1412, "nome" => "Ermitão Maligno"],
  ["id" => 1413, "nome" => "Ermitão Selvagem"],
  ["id" => 1415, "nome" => "Leopardo Filhote"],
  ["id" => 1416, "nome" => "Ninfa Perversa"],
  ["id" => 1417, "nome" => "Zipper"],
  ["id" => 1418, "nome" => "Serpente Suprema"],
  ["id" => 1492, "nome" => "Samurai Encarnado"],
  ["id" => 1493, "nome" => "Dríade"],
  ["id" => 1494, "nome" => "Besouro-Rei"],
  ["id" => 1495, "nome" => "Atirador de Pedras"],
  ["id" => 1497, "nome" => "Golem de Madeira"],
  ["id" => 1498, "nome" => "Artilheiro Wootan"],
  ["id" => 1499, "nome" => "Guerreiro Wootan"],
  ["id" => 1500, "nome" => "Parasita"],
  ["id" => 1503, "nome" => "Árvore Maldita"],
  ["id" => 1504, "nome" => "Dullahan"],
  ["id" => 1505, "nome" => "Loli Ruri"],
  ["id" => 1506, "nome" => "Mascarado"],
  ["id" => 1507, "nome" => "Serial Killer"],
  ["id" => 1508, "nome" => "Quve"],
  ["id" => 1509, "nome" => "Lude"],
  ["id" => 1510, "nome" => "Poltergeist"],
  ["id" => 1511, "nome" => "Amon-Rá"],
  ["id" => 1512, "nome" => "Yao Jun"],
  ["id" => 1513, "nome" => "Mao Guai"],
  ["id" => 1514, "nome" => "Zhu Po Long"],
  ["id" => 1515, "nome" => "Filhote de Hatii"],
  ["id" => 1516, "nome" => "Mi Gao"],
  ["id" => 1517, "nome" => "Jing Guai"],
  ["id" => 1519, "nome" => "Chung E"],
  ["id" => 1582, "nome" => "Deviling"],
  ["id" => 1583, "nome" => "Tao Gunka"],
  ["id" => 1584, "nome" => "Tamruan"],
  ["id" => 1586, "nome" => "Gato de Folha"],
  ["id" => 1587, "nome" => "Kraben"],
  ["id" => 1588, "nome" => "Orc Natalino"],
  ["id" => 1613, "nome" => "Metaling"],
  ["id" => 1614, "nome" => "Mineral"],
  ["id" => 1615, "nome" => "Obsidiana"],
  ["id" => 1616, "nome" => "Mineiros"],
  ["id" => 1617, "nome" => "Fornalha Velha"],
  ["id" => 1618, "nome" => "Ungoliant"],
  ["id" => 1619, "nome" => "Porcellio"],
  ["id" => 1620, "nome" => "Nuvem Tóxicas"],
  ["id" => 1621, "nome" => "Nuvem Venenosa"],
  ["id" => 1622, "nome" => "Ursinho"],
  ["id" => 1623, "nome" => "RSX-0806"],
  ["id" => 1627, "nome" => "Anopheles"],
  ["id" => 1628, "nome" => "Holden"],
  ["id" => 1630, "nome" => "Lady Branca"],
  ["id" => 1632, "nome" => "Gremlin"],
  ["id" => 1633, "nome" => "Beholder"],
  ["id" => 1634, "nome" => "Seyren Windsor"],
  ["id" => 1635, "nome" => "Eremes Guile"],
  ["id" => 1636, "nome" => "Howard Alt-Eisen"],
  ["id" => 1637, "nome" => "Margaretha Sorin"],
  ["id" => 1638, "nome" => "Cecil Damon"],
  ["id" => 1639, "nome" => "Kathryne Keyron"],
  ["id" => 1652, "nome" => "Egnigem Cenia"],
  ["id" => 1653, "nome" => "Wickebine Tres"],
  ["id" => 1654, "nome" => "Armeyer Dinze"],
  ["id" => 1655, "nome" => "Errende Ebecee"],
  ["id" => 1656, "nome" => "Kavach Icarus"],
  ["id" => 1657, "nome" => "Laurell Weinder"],
  ["id" => 1668, "nome" => "Archdam"],
  ["id" => 1670, "nome" => "Dimik (verde)"],
  ["id" => 1671, "nome" => "Dimik (azul)"],
  ["id" => 1672, "nome" => "Dimik (laranja)"],
  ["id" => 1673, "nome" => "Dimik (vermelho)"],
  ["id" => 1676, "nome" => "Venatu (violeta)"],
  ["id" => 1677, "nome" => "Venatu (verde)"],
  ["id" => 1678, "nome" => "Venatu (laranja)"],
  ["id" => 1679, "nome" => "Venatu (azul)"],
  ["id" => 1680, "nome" => "Vento da Colina"],
  ["id" => 1681, "nome" => "Gemini-S58"],
  ["id" => 1682, "nome" => "Removedor"],
  ["id" => 1685, "nome" => "Vesper"],
  ["id" => 1686, "nome" => "Filhote de Orc"],
  ["id" => 1687, "nome" => "Grove"],
  ["id" => 1688, "nome" => "Lady Tanee"],
  ["id" => 1692, "nome" => "Breeze"],
  ["id" => 1693, "nome" => "Plasma (amarelo)"],
  ["id" => 1694, "nome" => "Plasma (vermelho)"],
  ["id" => 1695, "nome" => "Plasma (verde)"],
  ["id" => 1696, "nome" => "Plasma (violeta)"],
  ["id" => 1697, "nome" => "Plasma (azul)"],
  ["id" => 1698, "nome" => "Palavra Morta"],
  ["id" => 1699, "nome" => "Mímico Antigo"],
  ["id" => 1700, "nome" => "Dama de Guarda"],
  ["id" => 1701, "nome" => "Senhora do Abrigo"],
  ["id" => 1702, "nome" => "Baronesa da Retribuição"],
  ["id" => 1703, "nome" => "Lady Solace"],
  ["id" => 1704, "nome" => "Odium de Thanatos"],
  ["id" => 1705, "nome" => "Despero de Thanatos"],
  ["id" => 1706, "nome" => "Maero de Thanatos"],
  ["id" => 1707, "nome" => "Pesar de Thanatos"],
  ["id" => 1708, "nome" => "Memória de Thanatos"],
  ["id" => 1713, "nome" => "Acidus (amarelo)"],
  ["id" => 1714, "nome" => "Ferus (vermelho)"],
  ["id" => 1715, "nome" => "Novus"],
  ["id" => 1716, "nome" => "Acidus (azul)"],
  ["id" => 1717, "nome" => "Ferus (verde)"],
  ["id" => 1718, "nome" => "Novus"],
  ["id" => 1719, "nome" => "Detardeurus"],
  ["id" => 1720, "nome" => "Hydrolancer"],
  ["id" => 1721, "nome" => "Ovo de Dragão"],
  ["id" => 1734, "nome" => "Kiel D-01"],
  ["id" => 1735, "nome" => "Alicel"],
  ["id" => 1736, "nome" => "Aliot"],
  ["id" => 1737, "nome" => "Aliza"],
  ["id" => 1738, "nome" => "Constante"],
  ["id" => 1751, "nome" => "Valquíria Randgris"],
  ["id" => 1752, "nome" => "Skogul"],
  ["id" => 1753, "nome" => "Frus"],
  ["id" => 1754, "nome" => "Skeggiold (preto)"],
  ["id" => 1755, "nome" => "Skeggiold (azul)"],
  ["id" => 1768, "nome" => "Pesar Noturno"],
  ["id" => 1769, "nome" => "Agav"],
  ["id" => 1770, "nome" => "Echio"],
  ["id" => 1771, "nome" => "Vanberk"],
  ["id" => 1772, "nome" => "Isilla"],
  ["id" => 1773, "nome" => "Hodremlin"],
  ["id" => 1774, "nome" => "Rastreador"],
  ["id" => 1775, "nome" => "Yeti"],
  ["id" => 1776, "nome" => "Siroma"],
  ["id" => 1777, "nome" => "Titã de Gelo"],
  ["id" => 1778, "nome" => "Gazeti"],
  ["id" => 1779, "nome" => "Ktullanux"],
  ["id" => 1780, "nome" => "Muscipular"],
  ["id" => 1781, "nome" => "Drosera"],
  ["id" => 1782, "nome" => "Roween"],
  ["id" => 1783, "nome" => "Galion"],
  ["id" => 1784, "nome" => "Stapo"],
  ["id" => 1785, "nome" => "Atroce"],
  ["id" => 1796, "nome" => "Aunoe"],
  ["id" => 1797, "nome" => "Fanat"],
  ["id" => 1829, "nome" => "Espadachim Guardião"],
  ["id" => 1830, "nome" => "Arqueiro Guardião"],
  ["id" => 1831, "nome" => "Salamandra"],
  ["id" => 1832, "nome" => "Ifrit"],
  ["id" => 1833, "nome" => "Kasa"],
  ["id" => 1836, "nome" => "Magmaring"],
  ["id" => 1837, "nome" => "Imp"],
  ["id" => 1838, "nome" => "Golpeador"],
  ["id" => 1839, "nome" => "Byorgue"],
  ["id" => 1864, "nome" => "Massacre"],
  ["id" => 1865, "nome" => "Zumbi Dilacerado"],
  ["id" => 1866, "nome" => "Cão Infernal"],
  ["id" => 1867, "nome" => "Banshee"],
  ["id" => 1869, "nome" => "Crânio Flamejante"],
  ["id" => 1870, "nome" => "Necromante"],
  ["id" => 1871, "nome" => "Bispo Decadente"],
  ["id" => 1872, "nome" => "Mosca Infernal"],
  ["id" => 1873, "nome" => "Belzebu (mosca)"],
  ["id" => 1874, "nome" => "Belzebu"],
  ["id" => 1880, "nome" => "Leshij"],
  ["id" => 1881, "nome" => "Les"],
  ["id" => 1882, "nome" => "Baba-Yaga"],
  ["id" => 1883, "nome" => "Kikimora"],
  ["id" => 1884, "nome" => "Mavka"],
  ["id" => 1885, "nome" => "Gorynych"]
];